import {jetbrainsMono} from "@/app/ui";
import {NavBar} from "@/app/ui/navigation/NavBar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.className} antialiased`}
      >
    <NavBar/>
      {children}
      </body>
    </html>
  );
}
